# Versatile Adapter Configuration
server.port=8081

# App
versatile-adapter.adapter-app-name=VersatileAdapter

# Versatile Platform
versatile-adapter.versatile-url-template=http://100.100.135.203:31113/v1/mock_project_id/agents/fb723468-c8ca-424b-a95f-a3e74b37e090/conversations/{conversation_id}
versatile-adapter.versatile-timeout=600

# Logging
logging.level.root=INFO
logging.level.com.openjiuwen=DEBUG
