spring:
  application:
    name: demo-mcp-agent-service
  config:
    import:
      - optional:classpath:application-base.yml
      - optional:classpath:application-base_local.yml
      - optional:classpath:application-mcp.yml
