openjiuwen:
  service:
    middleware:
      memory:
        provider: jiuwen
        endpoint: ${JIUWEN_ENDPOINT:http://localhost:8516}
        encrypted-api-key: ${JIUWEN_API_KEY:}
        rerank: false
