/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.service.spec.concurrency;

/**
 * Observer for the admission permit lifecycle (DFX-002).
 *
 * <p>Invoked by the admission control component at the exact points where a
 * concurrency quota slot is acquired and released, so listeners observe
 * precisely the tasks that occupy admission quota — no more, no less. This
 * makes the listener the authoritative signal for quota-occupancy probes
 * (e.g. {@link ActiveTaskQuery} implementations): a task is visible from
 * {@code onAdmitted} until {@code onReleased}, matching
 * {@link TaskAdmissionGate#currentCount()}.
 *
 * <p>{@code onAdmitted} fires after a successful {@code tryAcquire()} and
 * {@code onReleased} fires in the same {@code finally} block that releases
 * the slot, including failure and cancellation paths. A rejected task is
 * never reported. {@code onAdmitted} is invoked inside the admission
 * try-finally scope: if it throws, the request fails but the quota slot is
 * still released and {@code onReleased} is still invoked as compensation —
 * implementations must tolerate receiving {@code onReleased} for a task
 * whose {@code onAdmitted} did not complete.
 *
 * <p>Defined in the base module so the A2A executor can pick up any listener
 * bean (typically the ext module's tracker) without depending on the ext
 * module's concrete implementation.
 *
 * @since 0.1.2
 */
public interface TaskAdmissionListener {
    /**
     * A quota slot has been acquired for a task.
     *
     * <p>Called inside the admission try-finally scope: if this method throws,
     * the request fails, the acquired slot is released, and {@link #onReleased}
     * is still invoked as compensation.
     *
     * @param taskId the task identifier; non-null on standard transport
     *        paths (generated by the A2A SDK when the client omits it)
     * @param conversationId the conversation identifier
     */
    void onAdmitted(String taskId, String conversationId);

    /**
     * The quota slot acquired for the task has been released (completion,
     * failure or cancellation).
     *
     * @param taskId the task identifier passed to {@link #onAdmitted}
     * @param conversationId the conversation identifier
     */
    void onReleased(String taskId, String conversationId);
}
