/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.openjiuwen.service.spec.concurrency;

/**
 * Observer for the admission permit lifecycle (DFX-002).
 *
 * <p>Invoked by the runtime's admission machinery at the exact points where
 * a concurrency quota slot is acquired and released, so listeners observe
 * precisely the tasks that occupy admission quota — no more, no less. This
 * makes the listener the authoritative signal for quota-occupancy probes
 * (e.g. {@link ActiveTaskQuery} implementations): a task is visible from
 * {@code onAdmitted} until {@code onReleased}, matching
 * {@link TaskAdmissionGate#currentCount()}.
 *
 * <p>Release follows the consequence-landed model (DFX-006): the
 * admission-release coordinator owns the permit from admission until the
 * round's terminal or interrupted event has been consumed by the main event
 * processor, with a TTL fallback that reclaims permits whose consequences
 * were lost. {@code onReleased} therefore typically fires after the
 * orchestrated processing has finished. A rejected task is never reported.
 *
 * <p>{@code onAdmitted} is invoked inside the executor's admission scope:
 * if it throws, the request fails and the release is deferred to the same
 * coordinator paths — at the latest the force cap — so implementations
 * must tolerate receiving {@code onReleased}, possibly much later and on
 * another thread, for a task whose {@code onAdmitted} did not complete,
 * and must not rely on any release timing relative to the request.
 *
 * <p>Defined in the base module so the A2A executor can pick up any listener
 * bean (typically the ext module's tracker) without depending on the ext
 * module's concrete implementation.
 *
 * @since 0.1.2
 */
public interface TaskAdmissionListener {
    /**
     * A quota slot has been acquired for a task.
     *
     * <p>Called inside the executor's admission scope, after the permit has
     * been acquired. If this method throws, the request fails; the release is
     * owned by the admission-release coordinator and still happens via its
     * consequence-landed or TTL paths, so {@link #onReleased} arrives
     * eventually — at the latest at the force cap.
     *
     * @param taskId the task identifier; non-null on standard transport
     *        paths (generated by the A2A SDK when the client omits it)
     * @param conversationId the conversation identifier
     */
    void onAdmitted(String taskId, String conversationId);

    /**
     * The quota slot acquired for the task has been released: the round's
     * consequences landed in the main event processor, or the coordinator's
     * TTL fallback reclaimed the permit. May run on the event-processor or
     * TTL-scheduler thread rather than the request thread.
     *
     * @param taskId the task identifier passed to {@link #onAdmitted}
     * @param conversationId the conversation identifier
     */
    void onReleased(String taskId, String conversationId);
}
